name: exercise_1
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-444.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  audio_video_progress_bar: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    #images 
    - assets/image/
    - assets/vector/
    - assets/
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/font/SF-Pro-Display/SF-Pro-Display-Thin.otf
          style: normal
          weight: 100
        - asset: assets/font/SF-Pro-Display/SF-Pro-Display-Light.otf
          style: normal
          weight: 300
        - asset: assets/font/SF-Pro-Display/SF-Pro-Display-Regular.otf
          style: normal
          weight: 400
        - asset: assets/font/SF-Pro-Display/SF-Pro-Display-Medium.otf
          style: normal
          weight: 500
        - asset: assets/font/SF-Pro-Display/SF-Pro-Display-SemiBold.otf
          style: normal
          weight: 600
        - asset: assets/font/SF-Pro-Display/SF-Pro-Display-Bold.otf
          style: normal
          weight: 700
        - asset: assets/font/SF-Pro-Display/SF-Pro-Display-Black.otf
          style: normal
          weight: 900
